# Generated by Django 6.1 on 2026-08-26 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('WEDDING', 'Wedding'), ('RECEPTION', 'Reception'), ('ENGAGEMENT', 'Engagement'), ('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('HOUSEWARMING', 'Housewarming'), ('CORPORATE', 'Corporate Event'), ('CONFERENCE', 'Conference'), ('SEMINAR', 'Seminar'), ('RELIGIOUS', 'Religious Event'), ('FAMILY', 'Family Function'), ('COMMUNITY', 'Community Program'), ('PRIVATE', 'Private Event'), ('CUSTOM', 'Custom Event')], max_length=20)),
                ('custom_event_type_label', models.CharField(blank=True, help_text='Used only when event_type is CUSTOM.', max_length=100)),
                ('host_name', models.CharField(blank=True, help_text='Name displayed on invitations as the host, if different from the organizer.', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('google_maps_link', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
