# Generated by Django 6.1 on 2026-09-10 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0003_guest_email'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=20)),
                ('wa_link', models.URLField(blank=True, help_text='Populated only for the WhatsApp channel.', max_length=1000)),
                ('status', models.CharField(choices=[('LINK_GENERATED', 'Link Generated'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='LINK_GENERATED', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='guests.guest')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='invitations.invitation')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
