# Generated by Django 6.1 on 2026-10-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='call_sid',
            field=models.CharField(blank=True, help_text="Twilio's CallSid for this call. Populated only for the Voice Call channel.", max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('VOICE_CALL', 'Voice Call')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('LINK_GENERATED', 'Link Generated'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CALLING', 'Calling')], default='LINK_GENERATED', max_length=20),
        ),
    ]
