# Generated by Django 6.1 on 2026-09-27 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymedia',
            name='face_scan_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', help_text='Whether this photo has been scanned for faces yet. Only IMAGE media is ever scanned.', max_length=10),
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encoding_json', models.TextField(help_text='JSON-encoded list of 128 floats (a face_recognition face encoding).')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='gallery.gallerymedia')),
            ],
            options={
                'db_table': 'gallery_face_embeddings',
            },
        ),
    ]
