# Generated by Django 6.1 on 2026-10-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerymedia_face_scan_status_faceembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymedia',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='File size in bytes, captured at upload time.', null=True),
        ),
    ]
