# Generated by Django 6.1 on 2026-08-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(upload_to='invitations/templates/')),
                ('background_image', models.ImageField(help_text='Base image used to render personalized invitations.', upload_to='invitations/templates/backgrounds/')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates are hidden from organizers.')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'invitation_templates',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_token', models.CharField(help_text="Unique token used in the guest's secure response link.", max_length=64, unique=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='invitations/generated/images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invitations/generated/pdfs/')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('FAILED', 'Failed')], default='GENERATED', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='guests.guest')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='invitations.invitationtemplate')),
            ],
            options={
                'db_table': 'invitations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('guest', 'template'), name='unique_invitation_per_guest_template')],
            },
        ),
    ]
