# Generated by Django 6.1 on 2026-10-03 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0004_guestcategory_guest_category_and_more'),
        ('invitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtemplate',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', help_text="Which send channel this template's content is designed for.", max_length=10),
        ),
        migrations.AddField(
            model_name='invitationtemplate',
            name='is_custom',
            field=models.BooleanField(default=False, help_text="True for an organizer's own uploaded template, False for a platform-provided one."),
        ),
        migrations.AddField(
            model_name='invitationtemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_invitation_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitationtemplate',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Base image used to render personalized invitations (Email/WhatsApp image-based sends). Not used for plain-text SMS templates.', null=True, upload_to='invitations/templates/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='invitationtemplate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='invitations/templates/'),
        ),
        migrations.CreateModel(
            name='InvitationSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('VOICE_CALL', 'Voice Call')], max_length=10)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED_QUOTA', 'Skipped (Quota Exceeded)'), ('PENDING_MANUAL', 'Pending Manual Confirmation')], default='PENDING_MANUAL', max_length=20)),
                ('is_reminder', models.BooleanField(default=False, help_text="True if this send was triggered by the reminder system rather than the organizer's initial send.")),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_sends', to='events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_sends', to='guests.guest')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_sends_made', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sends', to='invitations.invitationtemplate')),
            ],
            options={
                'db_table': 'invitation_sends',
                'ordering': ['-created_at'],
            },
        ),
    ]
