# Generated by Django 6.1 on 2026-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitationtemplate_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='rendered_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invitationtemplate',
            name='body_text',
            field=models.TextField(blank=True, help_text='Plain-text content using placeholders like {guest_name}, {event_name}, {event_date}, {event_time}, {venue_name}, {venue_address}, {host_name}. Required for WhatsApp/SMS templates (no image rendering for those channels); optional extra copy for Email templates.'),
        ),
        migrations.AlterField(
            model_name='invitationtemplate',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Base image used to render personalized invitations (Email image-based sends). Not used for WhatsApp/SMS templates.', null=True, upload_to='invitations/templates/backgrounds/'),
        ),
    ]
