# Generated by Django 6.1 on 2026-10-03 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('invitations', '0003_invitation_rendered_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtemplate',
            name='body_text',
            field=models.TextField(blank=True, help_text="Plain-text content using placeholders like {guest_name}, {event_name}, {event_date}, {event_time}, {venue_name}, {venue_address}, {host_name}, plus any of this template's own custom fields (see TemplateCustomField). Required for WhatsApp/SMS templates; optional extra copy for Email templates."),
        ),
        migrations.CreateModel(
            name='ActiveFilledTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_values', models.JSONField(default=dict, help_text='Confirmed values for the fixed standard placeholder fields (event_name, event_date, etc.), auto-filled from the event but editable at fill-time.')),
                ('custom_values', models.JSONField(default=dict, help_text="Confirmed values for this template's own custom fields (e.g. bride_name, groom_name).")),
                ('rendered_preview_text', models.TextField(blank=True, help_text='The fully-rendered body_text (all placeholders substituted except guest_name) shown as the separate confirmation preview.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_filled_templates', to='events.event')),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_filled_template', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_fills', to='invitations.invitationtemplate')),
            ],
            options={
                'db_table': 'active_filled_templates',
            },
        ),
        migrations.CreateModel(
            name='TemplateCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.SlugField(help_text='Used in body_text as {field_key}. Letters, numbers, underscores only.')),
                ('label', models.CharField(help_text='Human-readable prompt shown on the fill-in form, e.g. "Bride\'s Name".', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='invitations.invitationtemplate')),
            ],
            options={
                'db_table': 'invitation_template_custom_fields',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('template', 'field_key'), name='unique_custom_field_key_per_template')],
            },
        ),
    ]
