# Generated by Django 6.1 on 2026-10-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_invitationtemplate_body_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtemplate',
            name='body_text',
            field=models.TextField(blank=True, help_text="Plain-text content using placeholders like {guest_name}, {event_name}, {event_date}, {event_time}, {venue_name}, {venue_address}, {host_name}, plus any of this template's own custom fields (see TemplateCustomField). Required for WhatsApp/SMS/Voice Call templates (Voice Call text is read aloud via text-to-speech); optional extra copy for Email templates."),
        ),
        migrations.AlterField(
            model_name='invitationtemplate',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('VOICE_CALL', 'Voice Call')], default='EMAIL', help_text="Which send channel this template's content is designed for.", max_length=10),
        ),
    ]
