# Generated by Django 6.1 on 2026-10-04 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0004_guestcategory_guest_category_and_more'),
        ('invitations', '0005_alter_invitationtemplate_body_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delay_hours', models.PositiveIntegerField(help_text="Hours after the guest's invitation was sent before a reminder is due, if they still haven't responded.")),
                ('is_active', models.BooleanField(default=True, help_text='Inactive schedules are kept for history but no longer trigger reminders.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='guests.guestcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='events.event')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='guests.guest')),
            ],
            options={
                'db_table': 'reminder_schedules',
            },
        ),
        migrations.CreateModel(
            name='PendingWhatsAppReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_at', models.DateTimeField(help_text='When this reminder became due (for display/sorting, not a deadline).')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_whatsapp_reminders', to='events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_whatsapp_reminders', to='guests.guest')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_whatsapp_reminders', to='invitations.reminderschedule')),
            ],
            options={
                'db_table': 'pending_whatsapp_reminders',
                'ordering': ['due_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reminderschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('guest__isnull', True)), models.Q(('category__isnull', True), ('guest__isnull', False)), _connector='OR'), name='reminder_schedule_exactly_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='reminderschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False), ('is_active', True)), fields=('category',), name='one_active_schedule_per_category'),
        ),
        migrations.AddConstraint(
            model_name='reminderschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('guest__isnull', False), ('is_active', True)), fields=('guest',), name='one_active_schedule_per_guest'),
        ),
        migrations.AddConstraint(
            model_name='pendingwhatsappreminder',
            constraint=models.UniqueConstraint(fields=('guest',), name='one_pending_whatsapp_reminder_per_guest'),
        ),
    ]
