# Generated by Django 6.1 on 2026-08-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=20)),
                ('family_member_count', models.PositiveIntegerField(default=3, help_text='Used for expected attendance calculation.')),
                ('invitation_status', models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='NOT_SENT', max_length=20)),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('MAYBE', 'Maybe')], default='PENDING', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
            options={
                'db_table': 'guests',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'mobile_number'), name='unique_guest_per_event')],
            },
        ),
    ]
