# Generated by Django 6.1 on 2026-08-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When the guest submitted their Accept/Reject/Maybe response.', null=True),
        ),
    ]
