# Generated by Django 6.1 on 2026-09-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_responded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, help_text="Optional. Required only if the organizer sends this guest's invitation via email.", max_length=254),
        ),
    ]
