# Generated by Django 6.1 on 2026-10-03 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0003_guest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_categories', to='events.event')),
            ],
            options={
                'db_table': 'guest_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='guests.guestcategory'),
        ),
        migrations.AddConstraint(
            model_name='guestcategory',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_category_name_per_event'),
        ),
    ]
