# Generated by Django 6.1 on 2026-09-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerEventAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False by the organizer to revoke access immediately.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. If set, access is treated as revoked after this time even if is_active is still True.', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_access_grants', to='events.event')),
                ('granted_by', models.ForeignKey(help_text='The organizer who granted this access.', on_delete=django.db.models.deletion.CASCADE, related_name='granted_photographer_access', to=settings.AUTH_USER_MODEL)),
                ('photographer', models.ForeignKey(limit_choices_to={'role': 'PHOTOGRAPHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'photographer_event_access',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'photographer'), name='unique_photographer_per_event')],
            },
        ),
    ]
