# Generated by Django 6.1 on 2026-08-24 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Number of days this plan is valid for after activation.')),
                ('guest_limit', models.PositiveIntegerField(default=50, help_text='Maximum number of guests allowed per event.')),
                ('event_limit', models.PositiveIntegerField(default=1, help_text='Maximum number of active events allowed.')),
                ('template_limit', models.PositiveIntegerField(default=1, help_text='Maximum number of invitation templates accessible.')),
                ('storage_limit_mb', models.PositiveIntegerField(default=500, help_text='Maximum media storage allowed, in megabytes.')),
                ('gallery_enabled', models.BooleanField(default=True)),
                ('qr_code_enabled', models.BooleanField(default=True)),
                ('photographer_access_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans are hidden from new subscriptions.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order plans are shown on the pricing page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'membership_plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='memberships.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
