# Generated by Django 6.1 on 2026-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='template_limit',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='templates',
            field=models.ManyToManyField(blank=True, help_text='The specific invitation templates organizers on this plan may use.', related_name='plans', to='invitations.invitationtemplate'),
        ),
    ]
