# Generated by Django 6.1 on 2026-10-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_remove_membershipplan_template_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='templates',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='template_limit',
            field=models.PositiveIntegerField(blank=True, default=5, help_text="Maximum number of templates (platform-provided plus the organizer's own custom uploads) usable on this plan. Null means unlimited.", null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='total_invitations',
            field=models.PositiveIntegerField(blank=True, default=100, help_text="Total invitation sends allowed for the subscription's lifetime, shared across WhatsApp, Email, and SMS channels. Null means unlimited.", null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='voice_call_limit',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Total automated voice-call invitations allowed for the subscription's lifetime. Separate from total_invitations since a call costs far more per unit than a text-based send. Null means unlimited, 0 means voice calling is not available on this plan.", null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='invitations_used',
            field=models.PositiveIntegerField(default=0, help_text="Invitations sent so far (WhatsApp+Email+SMS combined) against this subscription's total_invitations."),
        ),
        migrations.AddField(
            model_name='subscription',
            name='voice_calls_used',
            field=models.PositiveIntegerField(default=0, help_text="Automated voice calls placed so far against this subscription's voice_call_limit."),
        ),
    ]
