# Generated by Django 6.1 on 2026-10-03 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitationtemplate_channel_and_more'),
        ('memberships', '0003_remove_membershipplan_templates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerTemplateLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_library_entries', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='invitations.invitationtemplate')),
            ],
            options={
                'db_table': 'organizer_template_library',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('organizer', 'template'), name='unique_organizer_template_library_entry')],
            },
        ),
    ]
