# Generated by Django 6.1 on 2026-10-04 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_organizertemplatelibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformChannelPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('VOICE_CALL', 'Voice Call')], max_length=20, unique=True)),
                ('total_capacity', models.PositiveIntegerField(default=0, help_text='Total units ever topped up for this channel (cumulative, not a current balance).')),
                ('used', models.PositiveIntegerField(default=0, help_text='Units consumed so far against total_capacity.')),
                ('low_balance_threshold', models.PositiveIntegerField(default=100, help_text='Remaining balance at or below which the admin dashboard flags this channel as low.')),
            ],
            options={
                'db_table': 'platform_channel_pools',
            },
        ),
        migrations.CreateModel(
            name='TopupPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Shown to organizers, e.g. "50 Invitations" or "20 Voice Calls".', max_length=100)),
                ('kind', models.CharField(choices=[('INVITATIONS', 'Invitations'), ('VOICE_CALLS', 'Voice Calls')], max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='How many invitations or voice calls this pack adds when purchased.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive packs are hidden from organizers but keep existing purchase history intact.')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'topup_packs',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='invitations_topup',
            field=models.PositiveIntegerField(default=0, help_text="Extra invitation allowance purchased via TopupPurchase, added on top of the plan's total_invitations."),
        ),
        migrations.AddField(
            model_name='subscription',
            name='voice_calls_topup',
            field=models.PositiveIntegerField(default=0, help_text="Extra voice-call allowance purchased via TopupPurchase, added on top of the plan's voice_call_limit."),
        ),
        migrations.CreateModel(
            name='PlatformPoolTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(help_text="Units added to the pool's total_capacity by this top-up.")),
                ('note', models.CharField(blank=True, help_text='Optional admin note, e.g. "Twilio SMS credit purchase - invoice #1234".', max_length=255)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='memberships.platformchannelpool')),
                ('topped_up_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_pool_topups_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_pool_topups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopupPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_checkout_session_id', models.CharField(max_length=200, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='memberships.topuppack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topup_purchases',
                'ordering': ['-created_at'],
            },
        ),
    ]
