# Generated by Django 6.1 on 2026-09-27 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('gallery', '0002_gallerymedia_face_scan_status_faceembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Opaque public identifier embedded in the QR code's URL. Never the event's numeric id.", unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Organizer can deactivate a QR code (e.g. event postponed/cancelled) without deleting it.')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='events.event')),
            ],
            options={
                'db_table': 'event_qr_codes',
            },
        ),
        migrations.CreateModel(
            name='GuestSelfieSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfie_sessions', to='events.event')),
                ('matched_media', models.ManyToManyField(blank=True, related_name='matched_selfie_sessions', to='gallery.gallerymedia')),
            ],
            options={
                'db_table': 'guest_selfie_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
