# Generated by Django 6.1 on 2026-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mobileotp_delete_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Set by an admin to block login without deleting the account.'),
        ),
    ]
