# Generated by Django 6.1 on 2026-10-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_suspended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Set by an admin to block this user from logging in.'),
        ),
    ]
